BUG/MINOR: build: Make sure openssl is up to date when signing rpms
On an (old?) el10 build image, I have seen this error resulting in
broken rpm commands. This seams to be caused by installation of
rpm-sign, which updates other rpm/rpm-* packages, especially
rpm-sequoia, but is missing a dependency on an openssl-libs update.

rpmspec: symbol lookup error: /lib64/librpm_sequoia.so.1: undefined symbol: \
    EVP_PKEY_verify_message_init, version OPENSSL_3.4.0
rpmbuild: symbol lookup error: /lib64/librpm_sequoia.so.1: undefined symbol: \
    EVP_PKEY_verify_message_init, version OPENSSL_3.4.0